### ISSUE TITLE
Array is too big error

### ISSUE THREAD

**Issue by IVarha** [vanandrew/brainextractor#6]
Hello, thank you for a nice implementation. I found some bug/limitation on it. 
With some images I am getting error.

```
[FD]   warnings.warn(
[FD] Traceback (most recent call last):
[FD]   File "/mnt/c/Users/h492884/PycharmProjects/slicer_MER/slicer_plugin/model/Resources/py/bet.py", line 13, in <module>
[FD]     bet.run()
[FD]   File "/home/user/slic_build/python-install/lib/python3.9/site-packages/brainextractor/main.py", line 287, in run
[FD]     self.step_of_deformation(
[FD] ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

**Comment by vanandrew** [comment]
I think I need more information to be able to help. How large is the image that you are trying to brain extract?

**Comment by vanandrew** [comment]
Closing due to inactivity. Please reopen if you have more information.
